spring:
  application:
    name: project

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

# JWT KEY
jwt:
  secret: 7c1f65025d455f4fbeef6a9f14d54f86b700bcd2d96f8e2c9be38882f25bef18

